### ISSUE TITLE
KopiJS #38 - Saturday, 4th November

### ISSUE THREAD

**Issue by kenzoarima** [KopiJS/kopi.js#61]
<img width="668" alt="photogenic shot" src="https://heypearllee.files.wordpress.com/2016/12/dal-komm-coffee-singapore-3.jpg">

Fancy coffee, or fancy bingsu? Why not both! Join us as KopiJS checks out dal.komm coffee cafe! A mystery guest might fly by _(literally)_ to join in the fun too! :airplane: 

[**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Saturday, 4 November 2017, 10:57AM**
🗺  Location: [**dal.komm Coffee**](http://www.dalkomm.com.sg/) ([Foursquare](https://foursquare.com/v/dalkomm-coffee/5842619baf5c144c4e2b676a)), [#01-01/02, 176 Orchard Road, The Centrepoint. Nearest MRT: Somerset](https://www.google.com/maps/place/dal.komm+COFFEE/@1.3013865,103.8388035,18z/data=!4m5!3m4!1s0x31da1996b872dc4d:0xb4d79cfb7f682743!8m2!3d1.3013811!4d103.8398978)

> Agenda: Gather. Chope. Drink. Eat. Stickers. Selfies.

#### Notes

- No free food. Bring your own money.
- If you're lost or late, please [Messenger me](https://m.me/cheeaun), [Messenger us](https://m.me/g/AbYWHb6pTeBC7zJ6), or [ping the chatroom](http://kopijs.herokuapp.com/).
- The owner of the place is not aware of the meetup so don't ask him/her about it.
- RSPV is **OPTIONAL** (:+1: here). Just join whenever you feel like it, no pressure :coffee:

**Comment by robertsky** [comment]
what a weird timing. 10.57am. any significance behind it?

**Comment by cheeaun** [comment]
@robertsky why do you think it's weird? 😛

**Comment by joelkek** [comment]
Thanks for organizing! Was lovely meeting everyone and hearing about the wonderful things y’all are up to :D

**Comment by cheeaun** [comment]
Everyone, thanks for coming! 😁

### 📷 Photos

- https://www.facebook.com/miccheng/posts/10155842471682229 (Private)
- https://www.facebook.com/triplez82/posts/10155121352583123 (Private)
- https://twitter.com/kerion7/status/926646943396200450
- https://twitter.com/kerion7/status/926828827052949504
- https://twitter.com/cheeaun/status/926646986425507840
- https://twitter.com/kerion7/status/926655049849122816
- Any other photos?

### 👨‍👩‍👧‍👦 Attendees

- Me 😎 
- @kenzoarima 😎👕
- @khorkexin 😎💁 
- @vaibhavsagar
- @joelkek
- @oliviale 🍰 🆓 
- @laktek 🍫 
- @heliumlife + 1
- @jacobtyq
- @sebdeckers
- @tatatee 🍰 🆓 🙏 
- @miccheng
- @weimankow 
- @alvinchangw
- @iynaix 👕 ⌨️ 
- @juslee 📱⚔️ 
- @dandelia 
- @joerx
- @shortdiv
- @creativepsyco
- @PicoCreator
- @shiling
- [Ka Ho](https://www.facebook.com/einfinity.evoxenon)
- [Archi](https://www.facebook.com/archibald.visiting/)
- Anyone else?

### 🗒 Notes

- Pretty spacious place, though the entrance is quite unintuitive. Very visible from the outside but the entrance is inside 😅  Fortunately quite a central place with lots of nearby bus stops and MRT station 🗺 
- Since the entrance is quite uh.. unique, we stayed at two tall tables first, then moved to a curved long table formation but as more folks came in, we pivoted to two smaller tables nearby 🏓
- @laktek bought Tim Tams and *something* fingers(?)! 🍫 
- @joerx remembered to bring stickers! But everyone else forgot to bring theirs 😅  Next time need to do more reminders I think 🤔 
- For some folks, they perceived 10:57AM as 10:30AM, but in the end most folks attended late anyway so I guess it's fine ⏲ 
- Looks like not many folks try the cakes, some try the gooey bread thing 🍞 Some tried the bingsu while most just drink coffee (with much explanation on K1 - K4 beans) ☕️💥 
- @SheldonCheng [participated remotely](https://twitter.com/sheldytox/status/926741515358965760) so that's pretty awesome 👕 
- @kenzoarima got a free(?) birthday cake with a candle 🕯  from @oliviale 🍰 and I didn't get to eat it whattt 😩 
- @coffeesam unfortunately couldn't make it due to his venture into queueing for the iPhone X and reminiscing about the iPhone 1 📱  Fortunately we manage to abuse @juslee 's iPhone X 😈 
- Turns out @sayanee and @notthetup is just opposite us all this while (library @ orchard), giving a talk on [how to be the best podcaster in the world!](https://www.instagram.com/p/BbEGKUkhJS4/?hl=en&taken-by=triplez82) 🌏 🗣 

Alright, closing the issue now...

**Comment by khorkexin** [comment]
haha iphoneX is indeed the highlight! 📱⚔️

**Comment by valentine** [comment]
@cheeaun it's [Coles Lamington Fingers](https://en.wikipedia.org/wiki/Lamington). 💥

**Comment by sebdeckers** [comment]
@laktek was there too?! How did I miss him 🙈
