### ISSUE TITLE
Kopi.JS + RubySG 2017 - #39 - Tuesday, 26th December 

### ISSUE THREAD

**Issue by khorkexin** [KopiJS/kopi.js#62]
![kopi-ruby-wantedly](https://user-images.githubusercontent.com/2296/33948677-6b7fc032-e062-11e7-98bd-33cd3f78614d.jpg)

Join us in our end-of-year gathering, at WeWork's newly-launched co-working space!
This gathering is co-organised together with our friends from [RubySG](http://ruby.sg/).
Come catch up with folks from the Kopi.JS and RubySG communities, over snacks and soft drinks!
Main event is from 6:30 - 7:30pm. Feel free to mingle and hang out after that.

> [**Kopi.JS**](http://kopijs.org/) is a casual social gathering for engineers, designers and makers in Singapore. We hang out together, drink kopi and talk about almost anything!

⚠️ **JavaScript is NOT required**.

🗓  Date: **Tuesday, 26 December 2017, 6.30pm**
🗺  Location: [WeWork Beach Centre](https://goo.gl/maps/68K6TUNYFeB2), 15 Beach Rd, Singapore 189667

**👉 RSVP here: https://ti.to/rubysg/kopijs-rubysg-2017 👈**

Brought to you by [Wantedly](https://sg.wantedly.com/)

**Comment by cheeaun** [comment]
📢 Folks, note that you **MUST RSVP** for this event!

**Comment by valentine** [comment]
Thanks for organising today! It was great seeing everyone again!

Just wanted to mention that WeWork's main doors on street level (leading to the lifts) seem to require keycard access after a certain time (7pm?), and it'll probably be useful to leave some contact information and/or signage in case people get stranded outside.

**Comment by khorkexin** [comment]
hey @valentine great seeing you today too! the main entrance of wework is actually at level 2, which leads you to the reception area. moving forward, we'll communicate clearer that the venue is at level 2 (should we host it at wework beach centre again). thanks for the suggestion!

**Comment by valentine** [comment]
Sorry, I think I was referring to Beach Centre's main entrance instead. Just a heads up in case anyone based out of WeWork decides to host evening events in the future!

**Comment by cheeaun** [comment]
Everyone, thanks for coming! 😁

### 📷 Photos

- https://twitter.com/cheeaun/status/945597769733017600
- Any other photos?

### 👨‍👩‍👧‍👦 Attendees

- Me 😎
- @hanmd82
- @thenglee
- @khorkexin
- and few more: https://www.meetup.com/Singapore-Ruby-Group/events/245856319/attendees

🗒 Notes

- WeWork location is pretty central so it's easy to find. Building is a bit weird as some people couldn't find the entrance. Outside glassdoor were locked after 7PM so some people were stranded, and no idea if some people gave up since cannot enter or find entrance. Next time need to mention on event page that the entrance is on second floor and put signs (meetup + arrow) outside to guide people to go in. The barricade outside is also confusing as it looks like the entrance is under construction. The work spaces on the ground floor is also confusing because those are *other* companies which you can't find an entrance to go in (but only can peep at them via the glasses).
- Inside WeWork, the door needs someone to keep pressing to open (hodor). There were not enough chairs for everyone to chill since most people just stand. No one really goes to sit at the workstation-like tables to talk.
- Pizza (6 pieces?) were not enough for everyone. Salted egg yolk chips were not enough. Someone go and finish the whole bag of chips all by himself.
- Really glad that **Pheng Heong** helped out by updating folks in the [Meetup.com comments](https://www.meetup.com/Singapore-Ruby-Group/events/245856319/) on the pizzas, chocolates, snacks, beers and stickers.

Alright, closing the issue now...
